image: maven:3-jdk-11

stages:
  - build
  - unit-test
  - staging

maven-builds:
    image: maven:3-jdk-8
    stage: build
    script: "mvn --batch-mode -- errors --fail-fast --fail-at-end --show-version -installAtEnd-false - deplotAtEnd-false clean compile"
    artifacts:
      paths:
        - target/*.jar

test:
    image: maven
    stage: staging
    before_script:
      - gem install dpl
      - wget -q0- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    script :
        - dpl --provider-heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
        - export HEROKU_API_KEY=$HEROKU_APIKEY
        - heroku run --app $HEROKU_APPNAME migrate
    environment :
        name: staging
        url : $HEROKU_APP_HOST

