image: maven:3-jdk-8

stages:
  - test


test:
    image: ruby:latest
    stage: test
    before_script:
      - gem install dpl
      - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    script :
        - dpl --provider-heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
        - export HEROKU_API_KEY=$HEROKU_APIKEY
        - heroku run --app $HEROKU_APPNAME migrate
    environment :
        name: staging
        url : $HEROKU_APP_HOST

